### ISSUE TITLE
Customizable license

### ISSUE THREAD

**Issue by florimondmanca** [cs01/create-python-package#1]
Hey, just tried using this tool to init a new Python package. Very neat. :+1:

Currently, an MIT license is generated, but:

- Although it's a good sensible default, we may not want to use MIT.
- The `author` is not filled in.

There's a great little tool called [`mklicense`](https://github.com/cezaraugusto/mklicense) which can be used to generate various licenses (with a certain sense of humour).

We could ask the `create-python-package` user if they're OK to use MIT (and ask for the author's name?) and if not make a subcall to `mklicense`.

**Comment by cs01** [comment]
Great suggestion. I initially built it just to make my workflow faster, but I think this and #2 make a lot of sense. 

`create-python-package` would be kind of like `yarn init`. It could be run with a `--yes` flag to run with defaults, otherwise it could be run interactively and ask about License, Pipenv/poetry/setup.py/others, author, etc.

I will add these features 😄

**Comment by florimondmanca** [comment]
Absolutely! `npm init` or `yarn init` is exactly the kind of interactive project setup workflow I am imagining for this project. :+1:

**Comment by cs01** [comment]
This has been added to 0.2.0.0. Options are MIT, GPLv3, apache2 and bsd3. Of course more can be added, but the templating system is now in place to add more if desired.

**Comment by florimondmanca** [comment]
Works great! Well done. :+1:
